# Generated by Django 3.1.2 on 2022-02-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('price', models.IntegerField(verbose_name='price')),
                ('image', models.CharField(max_length=1000, verbose_name='image')),
                ('release_date', models.CharField(max_length=30, verbose_name='release_date')),
                ('lte_exists', models.BooleanField(verbose_name='lte_exists')),
            ],
        ),
    ]
